### ISSUE TITLE
discord link not valid or epired

### ISSUE THREAD

**Issue by MisterDevilVRC** [JustSleightly/SleightlyBall#1]
please provide a link so i can get my phurchase please ;)

**Comment by JustSleightly** [comment]
@Thingey I just tested the button on gumroad and the URL seems to work fine

![JS_1ea09](https://github.com/JustSleightly/SleightlyBall/assets/75227041/2f614a9d-942c-401e-ba22-b3d02c6f8199)

But in case that doesn't work for you, try https://discord.sleightly.dev/

It is also at the link in my store description and on this documentation page :)

If you have further issues, reach out to me on discord `@justsleightly` and we can see if somethings going on

**Comment by MisterDevilVRC** [comment]
Entering url in browser now worked for the invite to popup, I was tring ot enter it directly into discord.
issue solved
